config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'donations' => 'pages#donations', as: 'donations'
resources :posts do
  resources :comments #сделали ссылки на комменты внутри юрл постов
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post #комментарии принадлежат к постам
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :delete_all #каждый пост имеет много комментариев
    validates :title, presence: true, length:{minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end
private def comment_params
 params.require(:comment).permit(:username, :body)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "ibivob47", except: [:index, :show]

    def index
@post = Post.all
    end

    def new
        @post = Post.new
    end

    def show
@post = Post.find(params[:id])
    end

    def edit
@post = Post.find(params[:id])

    end

    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if (@post.save)
            redirect_to @post
        else
            render 'new' #в случае отказа перезагрузка страницы
        end
    end

    def update
        @post = Post.find(params[:id])

        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit' #в случае отказа перезагрузка страницы
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private def post_params
params.require(:post).permit(:title, :body)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cccp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
   <h5 class="my-0 mr-md-auto font-weight-normal">CCCP</h5>
   <nav class="my-2 my-md-0 mr-md-3">
     <span class="p-2 text-dark"><%= link_to "Главная", home_path %> </span>
      <span class="p-2 text-dark"><%= link_to "Добавить новость", new_post_path %> </span>
      <span class="p-2 text-dark"><%= link_to "Задонатить разработчику", donations_path %> </span>

      <span class="p-2 text-dark"><%= link_to "Про нас", about_path %> </span>

   </nav>
 </div>
 <div class="container">

    <%= yield %>
</div>
  </body>
</html>

app/views/pages/donations.html.erb
<h2>Ваши донаты :D</h2>

app/views/posts/edit.html.erb
<h2>Редактирование новостей</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %> </div>


    <% end %>
<% end %>
<p>
    Заголовок<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
Основной текст<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <%= f.submit("Сохранить",{:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>Главные новости</h1>
<% @post.each do |post| %>
<div class="alert alert-secondary">


<h3> <%= post.title %> </h3>
<p> <%= post.body %> <%= link_to "Подробнее", post_path(post), :class => 'btn btn-outline-primary' %> </p>

</div>

<% end %>

app/views/posts/new.html.erb
<h2>Добавление новостей</h2>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %> </div>


    <% end %>
<% end %>
<p>
    Заголовок<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
Основной текст<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <%= f.submit("Добавить",{:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.title %>  </h2>
<p> <%= @post.body %> </p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-success' %>
<%= link_to "Удалить", post_path(@post), method: :delete, data:{confirm: "Хотите удалить статью?"},:class => 'btn btn-danger' %>
<p>

    </p>
<hr>
<h3>Комментарии</h3>
<% @post.comments.each do |comment| %>

<div class="alert alert-secondary">
<p><strong><%= comment.username %></strong>: <%= comment.body %></p>

</div>

<% end %>

<hr>
<h3>Добавление комментария</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>

<p>
    Ваше имя<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
</p>
<p>
Текст комментария<br>
<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <%= f.submit("Прокомментировать",{:class => 'btn btn-info'}) %>
</p>
<% end %>